services:
  python:
    build:
      dockerfile: ./${DOCKERFILE}
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - PRODUCTION=${PRODUCTION}
      - DB_URL=${DB_URL}
    volumes:
      - ./shared:/usr/src/shared:ro
      - ./.env:/usr/.env:ro
      - /etc/localtime:/etc/localtime
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app/src
        python main.py
    networks:
      - backnet
