services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    # ports:
    #  - 8081:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=https://${SUBDOMAIN_PHPMYADMIN}${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${SUBDOMAIN_PHPMYADMIN}${DOMAIN}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.tls=true"
    depends_on:
      - db
    networks:
      - backnet